language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install --upgrade pytest>=3.0.0
  - pip install tox-travis codecov
script: tox
after_success:
  - codecov
