language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pytest>=3.0.0
  - pip install coverage hypothesis codecov pyrsistent
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install mypy; fi
  - python setup.py install
script: ./runtests.sh
after_success:
  - codecov
